services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    volumes:
#      - .:/app
#    depends_on:
#      - redis
  redis:
    image: redis/redis-stack:7.2.0-v14
    container_name: "toker_redis"
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_USER=your_user
      - REDIS_PASSWORD=your_password
#    command: ["redis-server", "--requirepass", "your_password"]
    volumes:
      - redis-data:/data

volumes:
  redis-data: